//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 06:07:09 PM CEST 
//


package it.smartcommunitylab.aac.jaxbmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * List of identity provider authorities.
 * 			
 * 
 * <p>Java class for authorities complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authorities">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="authorityMapping" type="{http://aac.smartcommunitylab.it/jaxbmodel}authorityMapping" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="authorityMatching" type="{http://aac.smartcommunitylab.it/jaxbmodel}authorityMatching" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authorities", propOrder = {
    "authorityMapping",
    "authorityMatching"
})
public class Authorities {

    protected List<AuthorityMapping> authorityMapping;
    protected List<AuthorityMatching> authorityMatching;

    /**
     * Default no-arg constructor
     * 
     */
    public Authorities() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public Authorities(final List<AuthorityMapping> authorityMapping, final List<AuthorityMatching> authorityMatching) {
        this.authorityMapping = authorityMapping;
        this.authorityMatching = authorityMatching;
    }

    /**
     * Gets the value of the authorityMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorityMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorityMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorityMapping }
     * 
     * 
     */
    public List<AuthorityMapping> getAuthorityMapping() {
        if (authorityMapping == null) {
            authorityMapping = new ArrayList<AuthorityMapping>();
        }
        return this.authorityMapping;
    }

    /**
     * Gets the value of the authorityMatching property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorityMatching property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorityMatching().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorityMatching }
     * 
     * 
     */
    public List<AuthorityMatching> getAuthorityMatching() {
        if (authorityMatching == null) {
            authorityMatching = new ArrayList<AuthorityMatching>();
        }
        return this.authorityMatching;
    }

}
