//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 06:07:09 PM CEST 
//


package it.smartcommunitylab.aac.jaxbmodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authority.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="authority">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ROLE_USER"/>
 *     &lt;enumeration value="ROLE_CLIENT"/>
 *     &lt;enumeration value="ROLE_ANY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "authority")
@XmlEnum
public enum Authority {

    ROLE_USER,
    ROLE_CLIENT,
    ROLE_ANY;

    public String value() {
        return name();
    }

    public static Authority fromValue(String v) {
        return valueOf(v);
    }

}
