//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 06:07:09 PM CEST 
//


package it.smartcommunitylab.aac.jaxbmodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.smartcommunitylab.aac.jaxbmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Services_QNAME = new QName("http://aac.smartcommunitylab.it/jaxbmodel", "services");
    private final static QName _Authorities_QNAME = new QName("http://aac.smartcommunitylab.it/jaxbmodel", "authorities");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.smartcommunitylab.aac.jaxbmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link Authorities }
     * 
     */
    public Authorities createAuthorities() {
        return new Authorities();
    }

    /**
     * Create an instance of {@link AuthorityMapping }
     * 
     */
    public AuthorityMapping createAuthorityMapping() {
        return new AuthorityMapping();
    }

    /**
     * Create an instance of {@link AuthorityMatching }
     * 
     */
    public AuthorityMatching createAuthorityMatching() {
        return new AuthorityMatching();
    }

    /**
     * Create an instance of {@link ResourceMapping }
     * 
     */
    public ResourceMapping createResourceMapping() {
        return new ResourceMapping();
    }

    /**
     * Create an instance of {@link ResourceDeclaration }
     * 
     */
    public ResourceDeclaration createResourceDeclaration() {
        return new ResourceDeclaration();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Match }
     * 
     */
    public Match createMatch() {
        return new Match();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Services }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aac.smartcommunitylab.it/jaxbmodel", name = "services")
    public JAXBElement<Services> createServices(Services value) {
        return new JAXBElement<Services>(_Services_QNAME, Services.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Authorities }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aac.smartcommunitylab.it/jaxbmodel", name = "authorities")
    public JAXBElement<Authorities> createAuthorities(Authorities value) {
        return new JAXBElement<Authorities>(_Authorities_QNAME, Authorities.class, null, value);
    }

}
