package it.smartcommunitylab.aac.spid.setupflow;

import org.springframework.mock.web.MockHttpSession;

/**
 * A Data Transfer Object (DTO) that holds the contextual state of a simulated
 * SPID SAML 2.0 authentication flow.
 * Generated by the {@link SpidRequestFlow},
 * this context encapsulates all the required payloads, session data, and SAML parameters
 * needed to complete or assert a mock Single Sign-On transaction.
 *
 * @param session       The simulated HTTP session maintaining the user's state and Spring Security context.
 * @param relayState    The SAML RelayState parameter, used to maintain state across the SSO redirect.
 * @param xmlRequest    The decoded, plain-text XML string representation of the AuthnRequest.
 * @param requestId     The unique ID of the AuthnRequest, used to validate the 'InResponseTo' attribute.
 * @param redirectedUrl The redirect url
 */
public record SpidRequest(MockHttpSession session, String relayState, String xmlRequest, String requestId,
                          String redirectedUrl) {

    /**
     * Internal constructor to bundle all the extracted and generated SAML parameters.
     *
     * @param session       The simulated HTTP session.
     * @param relayState    The SAML RelayState parameter.
     * @param xmlRequest    The decoded, plain-text XML string representation of the AuthnRequest.
     * @param requestId     The unique ID of the AuthnRequest.
     * @param redirectedUrl The redirect url.
     */
    public SpidRequest {
    }

    /**
     * @return The simulated HTTP session maintaining the user's state.
     */
    @Override
    public MockHttpSession session() {
        return session;
    }

    /**
     * @return The SAML RelayState parameter used across the SSO redirect.
     */
    @Override
    public String relayState() {
        return relayState;
    }

    /**
     * @return The decoded, plain-text XML string representation of the AuthnRequest.
     */
    @Override
    public String xmlRequest() {
        return xmlRequest;
    }

    /**
     * @return The unique ID of the AuthnRequest.
     */
    @Override
    public String requestId() {
        return requestId;
    }

    /**
     * @return The redirect url.
     */
    @Override
    public String redirectedUrl() {
        return redirectedUrl;
    }
}
