package it.smartcommunitylab.aac.spid.setupflow;

import org.springframework.mock.web.MockHttpSession;

/**
 * A Data Transfer Object (DTO) that holds the contextual state of a simulated
 * SPID SAML 2.0 authentication flow.
 * Generated by the {@link SpidRequestFlow},
 * this context encapsulates all the required payloads, session data, and SAML parameters
 * needed to complete or assert a mock Single Sign-On transaction.
 */
public class SpidRequest {

    /** The simulated HTTP session maintaining the user's state and Spring Security context. */
    private final MockHttpSession session;

    /** The SAML RelayState parameter, used to maintain state across the SSO redirect. */
    private final String relayState;

    /** The raw, Base64-encoded and deflated SAML AuthnRequest generated by the Service Provider. */
    private final String samlRequestEncoded;

    /** The decoded, plain-text XML string representation of the AuthnRequest. */
    private final String xmlRequest;

    /** The unique ID of the AuthnRequest, used to validate the 'InResponseTo' attribute. */
    private final String requestId;

    /** The redirect url */
    private final String redirectedUrl;

    /**
     * Internal constructor to bundle all the extracted and generated SAML parameters.
     * @param session The simulated HTTP session.
     * @param relayState The SAML RelayState parameter.
     * @param samlRequestEncoded The raw, Base64-encoded SAML AuthnRequest.
     * @param xmlRequest The decoded, plain-text XML string representation of the AuthnRequest.
     * @param requestId The unique ID of the AuthnRequest.
     * @param redirectedUrl The redirect url.
     */
    public SpidRequest(MockHttpSession session, String relayState,
                       String samlRequestEncoded, String xmlRequest, String requestId, String redirectedUrl) {
        this.session = session;
        this.relayState = relayState;
        this.samlRequestEncoded = samlRequestEncoded;
        this.xmlRequest = xmlRequest;
        this.requestId = requestId;
        this.redirectedUrl = redirectedUrl;
    }

    /** @return The simulated HTTP session maintaining the user's state. */
    public MockHttpSession getSession() { return session; }

    /** @return The SAML RelayState parameter used across the SSO redirect. */
    public String getRelayState() { return relayState; }

    /** @return The raw, Base64-encoded and deflated SAML AuthnRequest. */
    public String getSamlRequestEncoded() { return samlRequestEncoded; }

    /** @return The decoded, plain-text XML string representation of the AuthnRequest. */
    public String getXmlRequest() { return xmlRequest; }

    /** @return The unique ID of the AuthnRequest. */
    public String getRequestId() { return requestId; }

    /** @return The redirect url. */
    public String getRedirectedUrl() { return redirectedUrl; }
}
