name: Create and publish a Docker image
on:
  release:
    types: [published]
  workflow_dispatch:
      version:
        description: 'Build version'
        required: true
        type: string
      skip_tests:
        description: 'Skip tests'
        required: true        
        type: boolean        

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4       
      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Configure build
        id: configure-build
        run: |
          if [ ! -z "${{ github.release.name }}" ]; then
            echo "release"
            echo "version=${{ github.release.name }}" >> "$GITHUB_OUTPUT"
            echo "skip-tests=false" >> "$GITHUB_OUTPUT"
          elif [ ! -z "${{ github.inputs.version }}" ]; then
            echo "manual"
            echo "version=${{ github.inputs.version }}" >> "$GITHUB_OUTPUT"
            echo "skip-tests=${{ github.inputs.skip_tests }}" >> "$GITHUB_OUTPUT"
          else
            echo "snapshot"
            echo "version=SNAPSHOT" >> "$GITHUB_OUTPUT"
            echo "skip-tests=true" >> "$GITHUB_OUTPUT"
          fi        
    outputs:
      selected-stage: ${{ steps.select-stage.outputs.selected-stage }}          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "VER=${{ steps.configure-build.outputs.version }}"
            "SKIP_TESTS=${{ steps.configure-build.outputs.skip-tests }}"